Project-2/commerce/auctions/urls.py
from django.urls import path

from . import views

app_name = "auctions"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("categories/", views.categories, name="categories"),
    path("category/<int:category_id>", views.category, name="category"),
    path("create/", views.create, name="create"),
    path("<int:listing_id>", views.listing, name="listing"),
    path("<int:listing_id>/bidForm", views.bidForm, name="bidForm"),
    path("<int:listing_id>/commentForm", views.commentForm, name="commentForm"),
    path("closed_listing/<int:listing_id>", views.close_listing, name="close_listing"),
    path("watchlist/<int:user_id>", views.watchlist, name="watchlist"),
    path("<int:listing_id>/watchlist_add/", views.watchlist_add, name="watchlist_add"),
    path("<int:listing_id>/watchlist_remove/", views.watchlist_remove, name="watchlist_remove")
]

Project-2/commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

Project-2/commerce/auctions/models.py
from django.contrib.auth.models import AbstractUser, User
from django.db import models




class User(AbstractUser):
    watchlists = models.ManyToManyField("Listing", blank=True, related_name="watchlists")

    # def __str__(self):
    #     return f'{self.first_name} {self.last_name}'

class Category(models.Model):
    title = models.CharField(max_length=64, default="None")

    def __str__(self):
        return self.title

class Listing(models.Model):
    title = models.CharField(max_length=50, blank=True, null=True)
    description = models.CharField(max_length=120)
    active = models.BooleanField(default=True)
    image = models.CharField(max_length=200, blank=True, null=True)
    starting_bid = models.DecimalField(max_digits=5, decimal_places=2)
    current_bid = models.DecimalField(max_digits=5, decimal_places=2, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="owner")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="category")

    def __str__(self):
        return self.title

class Bid(models.Model):
    date_placed = models.DateField(auto_now_add=True)
    bid_amount = models.DecimalField(max_digits=5, decimal_places=2)
    winning_bid = models.BooleanField(default=False)
    listing_bid = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="listing_bids")
    user_bid = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_bids")
    # listings = models.ManyToManyField(Listing, blank=True, related_name="bids")

    # def __str__(self):
    #     return f'{self.id}: {self.bid_amount} by {user.username} for {listing.title}'    
    
class Comment(models.Model):
    date_placed = models.DateField(auto_now_add=True)
    comment_post = models.TextField()
    user_comment = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name="user_comments")
    listing_comment = models.ForeignKey(Listing, on_delete=models.CASCADE, blank=True, null=True, related_name="listing_comments")
    # user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comment_users")
    # listings = models.ManyToManyField(Listing, blank=True, related_name="comments")

Project-2/commerce/auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django import forms
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from django.shortcuts import render
from django.urls import reverse

from .models import Category, User, Listing, Bid

# Add new listing form class
class NewListingForm(forms.ModelForm):

    class Meta:
        model = Listing
        fields = ['title', 'description', 'image', 'starting_bid', 'user', 'category']

# login view provided
def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        print(user)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")

# logout view provided
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))

# register view provided
def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")

#Home page view
def index(request):
    return render(request, "auctions/index.html", {
        "listings": Listing.objects.all()
    })
    
#Create view
def create(request):
    if request.method == "POST":
        form = NewListingForm(request.POST)
        
        if form.is_valid():
            form.save()
            message = "Success! New listing saved. Add another?"
            return render(request, "auctions/create.html", {
                "form": NewListingForm(),
                "message": message
            })
        else:
            return render(request, "auctions/create.html", {
                "form": form
            })

    return render(request, "auctions/create.html", {
        "form": NewListingForm()
    })

#Individual Listing Page View
def listing(request, listing_id):
    listing = Listing.objects.get(id = listing_id)
    bids = listing.listing_bids.all()
    watchlists = listing.watchlists.all()
    # user = request.user
    # print(user)
    # non_watchlists = Users.objects.exclude(listings=listing).all()
    winning_bid_message = "Congratulations! Yours was the winning bid."
    return render(request, "auctions/listing.html", {
        "listing": listing,
        "bids": bids,
        "watchlists": watchlists,
        # "non_watchlists": non_watchlists,
        "winning_bid_message": winning_bid_message
    })

#Bid Form on Listing Page
def bidForm(request, listing_id):
    if request.method=="POST":
        listing = Listing.objects.get(pk=listing_id)
        user = request.user
        bids = listing.listing_bids.all()
        user_bid = user
        listing_bid = listing
        bid_amount = int(request.POST["bid_amount"])
        current_bid = listing.current_bid
        if bid_amount > current_bid:
          current_bid = bid_amount
          listing.save()
        #   return HTTPResponseRedirect(reverse("listing", kwargs=('listing_id':listing.id)))
        return render(request, "auctions/listing.html", {
            "listing": listing
        })

#Comments Form on Listing Page
def commentForm(request, listing_id):
    if request.method=="POST":
        listing = Listing.objects.get(pk=listing_id)
        user = request.user
        comments = listing.listing_comments.all()
        user_comment = user
        listing_comment = listing
        comment_post = request.POST["comment_post"]
        listing.listing_comments.add()

        # user_id = int(request.POST["user"])
        # user = User.objects.get(pk="user_id")
        return HTTPResponseRedirect(reverse("listing", args=(listing.id,)))

#Close Listing View
def close_listing(request, listing_id):
    if request.method=="POST":
        listing = Listing.objects.get(pk=listing_id)
        bids = listing.listing_bids.all()
        listing.active = False
        # if listing.current_bid >= listing.starting_bid:
        bid = Bid.objects.filter(bid_amount = listing.current_bid)
        bid.winning_bid = True
        # bid.listing_bid.save()
        listing.save()
        return render(request, "auctions/listing.html", {
            "listing": listing
        })
        # return HTTPResponseRedirect(reverse("listing", args=(listing.id,)))


#Watchlist Page View   
def watchlist(request, user_id):
    user = User.objects.get(id = user_id)
    watchlists = user.watchlists.all()
    listings = Listing.objects.all()
    print(user)
    return render(request, "auctions/watchlist.html", {
        "user": user,
        "watchlists": watchlists,
        "listings": listings
    })

#Add Watchlist 
def watchlist_add(request, listing_id):
    if request.method=="POST":
        listing = listing.objects.get(pk=listing_id)
        user = request.user 
        user.watchlists.add()
        return HTTPResponseRedirect(reverse("listing", args=(listing.id,)))

#Remove Watchlist 
def watchlist_remove(request, listing_id):
    if request.method=="POST":
        listing = listing.objects.get(pk=listing_id)
        user = request.user
        user.watchlists.delete()
        return HTTPResponseRedirect(reverse("listing", args=(listing.id,)))

#Categories Page View 
def categories(request):
    return render(request, "auctions/categories.html", {
        "categories": Category.objects.all()
    })

# Individual Category Page View
def category(request, category_id):
    category = Category.objects.get(id = category_id)
    listings = Listing.objects.filter(category = category)
    return render(request, "auctions/category.html", {
        "category": category,
        "listings": listings
    })

Project-2/commerce/auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block title %}
    Categories
{% endblock %}

{% block body %}
    <main class="categories">
        <h1>Auction Categories</h1>
        <ul>
            {% for category in categories %}
                <li class="categories">
                    <a href="{% url 'auctions:category' category.id %}">{{ category.id }}: {{ category.title }} </a>
                </li>
            {% endfor %}
        </ul>
    </main>
{% endblock %}

Project-2/commerce/auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}

{% block title %}
    Listing {{ title }}
{% endblock %}

{% block body %}
<main>
    <h1>Category: {{ category.title }}</h1>
    <ul>
        {% for listing in listings %}
            <li class="active-listings">
                <a href="{% url 'auctions:listing' listing.id %}">Listing {{ listing.id}}: {{ listing.title}} </a>
                <img src="../static/{{ listing.image }}"/>
                <p><b>Current Bid: </b> {{ listing.current_bid }}</p>
            </li>
        {% endfor %}
    </ul>
</main>
{% endblock %}

Project-2/commerce/auctions/templates/auctions/closed_listing.html
{% extends "auctions/layout.html" %}

{% block title %}
    Listing {{ title }}
{% endblock %}

{% block body %}
<main class="listing">
    <h1>Listing: {{ listing.title }}</h1>
    <div class="flex-wrapper">
        <div>
            <p><b>Title: </b>{{ listing.title}}</p>
            <p><b>Description: </b>{{ listing.description}}</p>
            <p><b>Category: </b>{{ listing.category}}</p>
            <p><b>Listing Owner: </b>{{ user.username}}</p>
        </div>
        <img src="../../static/{{ listing.image }}" />
    </div>
</main>
{% endblock %}

Project-2/commerce/auctions/templates/auctions/create.html
{% extends "auctions/layout.html" %}

{% block body %}
<main>
    <h1>Create a Listing</h1>
    <p class="success-message">{{ message }}</p>
    <form class="create-listing" action="{% url 'auctions:create' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
</main>
{% endblock %}

Project-2/commerce/auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block title %}
    Active Listings
{% endblock %}

{% block body %}
<main>
    <h1>Active Listings</h1>
    <ul>
        {% for listing in listings %}
            {% if listing.active %}
                <li class="active-listings">
                    <a href="{% url 'auctions:listing' listing.id %}">Listing {{ listing.id}}: {{ listing.title}} </a>
                    <img src="static/{{ listing.image }}"/>
                    <p><b>Current Bid: </b> {{ listing.current_bid }}</p>
                </li>
            {% endif %}
        {% endfor %}
    </ul>
</main>
{% endblock %}

Project-2/commerce/auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <script src="https://kit.fontawesome.com/ffa8d57923.js" crossorigin="anonymous"></script>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Zen+Kaku+Gothic+Antique:wght@300;400;500;700&display=swap" rel="stylesheet">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <header>
            <div><b>Project 2 - Auctions</b></div>
            <nav class="flex-wrapper">
                <div class="page-links">
                    <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
                    <a class="nav-link" href="{% url 'auctions:categories' %}">Categories</a>
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'auctions:watchlist' user.id %}">Watchlist</a>
                        <a class="nav-link" href="{% url 'auctions:create' %}">New Listing</a>
                    {% endif %}
                </div>
                
                {% if user.is_authenticated %}
                    <div class="signed-in">
                        <span>Welcome <strong>{{ user.username }}</strong>!</span>
                        <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                    </div>
                {% else %}
                    <div class="not-signed-in">
                        <span>Not signed in.</span>
                        <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                        <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                    </div>
                {% endif %}
            </nav>
        </header>
        <div class="main-content-wrapper">
            {% block body %}
            {% endblock %}
        </div>
        
        <footer>
            <span>Harvard Extension School</span>
            <span>CSCI E-33a &mdash; Spring 2022</span>
            <span>Reina McCuskey</span>
        </footer>
    </body>
</html>

Project-2/commerce/auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}

{% block title %}
    Listing {{ title }}
{% endblock %}

{% block body %}
<main class="listing">
    <h1>Listing: {{ listing.title }}</h1>
    <div class="flex-wrapper">
        <div>
            <p><b>Title: </b>{{ listing.title}}</p>
            <p><b>Description: </b>{{ listing.description}}</p>
            <p><b>Category: </b>{{ listing.category}}</p>
            <p><b>Listing Owner: </b>{{ user.username}}</p>
        </div>
        <img src="static/{{ listing.image }}" />
    </div>
   
    <div class="call-to-actions">
        <!--add option to close if user is owner-->
        {% if listing.user and listing.active %}
        <form action="closed_listing/{{listing.id}}" method="POST">
            {% csrf_token %}
            <button type="submit">Close listing</button>
        </form>  
        {% endif %}

        <!--add remove watchlist code-->
        <form action="" method="POST">
            {% if listing in user.objects.watchlists.all %}
                <button type="submit">Remove from watchlist</button>
            <!--else if active allow user to add to watchlist-->
            {% elif listing.active %}
                <button type="submit">Add to watchlist</button>
            {% endif %}
        </form>
        <!-- {% if listing in user.objects.watchlists.all %}
            <button type="submit" name="remove-from-watchlist">Remove from watchlist</button> -->
        <!--else if active allow user to add to watchlist-->
        <!-- {% elif listing.active %}
            <button type="submit" name="add-to-watchlist">Add to watchlist</button>
        {% endif %} -->
    </div>
     <!-- if active listing render forms -->
    {% if listing.active %}
        <form class="bid-watchlist-comment" action="{% url 'auctions:bidForm' listing.id %}" method="POST">
            {% csrf_token %}
            <div class="detail">
                <h2>Bids</h2>
                <p><b>Starting Bid: </b>{{ listing.starting_bid}}</p>
                <p><b>Current Bid: </b>{{ listing.current_bid}}</p>
                <label class="enter-bid">
                    <b>Enter a bid: </b>
                    <input type="number" step="any" name="bid_amount">
                </label>
                <input type="submit" value="Submit Bid" />
            </div> 
        </form> 
    
        <form class="bid-watchlist-comment" action="{% url 'auctions:commentForm' listing.id %}" method="POST">
            {% csrf_token %}
            <div class="detail">
                <div class="comments">
                    <h2>Comments</h2>
                    <label>
                        <b>New Comment:</b>
                        <textarea name="comment_post"></textarea>
                    </label>
                    <input type="submit" value="Post Comment" />
                </div>
                <div><span>(username)</span><p>Previous comment blah blah blah</p></div>
            </div>
        </form>
    {% endif %}
</main>
{% endblock %}

Project-2/commerce/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block title %}
    Login
{% endblock %}

{% block body %}
    <main class="login-page">
        <h1>Login</h1>

        {% if message %}
            <div>{{ message }}</div>
        {% endif %}

        <form action="{% url 'auctions:login' %}" method="post">
            {% csrf_token %}
            <label>
                <b>Username</b>
                <input autofocus type="text" name="username" placeholder="Username">
            </label>
            <label>
                <b>Password</b>
                <input type="password" name="password" placeholder="Password">
            </label>
            <input aria-label="submit login" type="submit" value="Login">
        </form>

        Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>
    </main>
    

{% endblock %}

Project-2/commerce/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block title %}
    Register
{% endblock %}

{% block body %}
    <main class="register-page">
        <h1>Register</h1>

        {% if message %}
            <div>{{ message }}</div>
        {% endif %}

        <form action="{% url 'auctions:register' %}" method="post">
            {% csrf_token %}
            <label>
                <b>Username</b>
                <input autofocus type="text" name="username" placeholder="Username">
            </label>
            <label>
                <b>Email</b>
                <input type="email" name="email" placeholder="Email Address">
            </label>
            <label>
                <b>Password</b>
                <input type="password" name="password" placeholder="Password">
            </label>
            <label>
                <b>Confirm Password</b>
                <input type="password" name="confirmation" placeholder="Confirm Password">
            </label>
            <input aria-label="submit registration" type="submit" value="Register">
        </form>

        Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>
    </main>
{% endblock %}

Project-2/commerce/auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block title %}
    Watchlists
{% endblock %}

{% block body %}
<main>
    <h1>My Watchlists</h1>
    <ul>
        {% for listing in watchlists %}
            <li class="closed-listings">
                <a href="{% url 'auctions:listing' listing.id %}">Listing #{{ listing.id}}: {{ listing.title }}</a>
            </li>
        {% empty %}
            <p>You have no assigned watchlists.</p>
        {% endfor %}
    </ul>
    
</main>
{% endblock %}