Project-1/wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("wiki/<str:title>/edit", views.edit_page, name="edit"),
    path("error/", views.error, name="errors"),
    path("random/", views.random_page, name="random"),
    path("wiki/", views.search, name="search"),
    path("wiki/<str:title>", views.entry, name="entry")
]

Project-1/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

Project-1/wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

Project-1/wiki/encyclopedia/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from markdown2 import Markdown
import random
from . import util


markdowner = Markdown()

# Create Entry class
class Entry():
    def __init__(self, title):
        self.title = title
        self.content = " "

# Add variable for initial values of entry titles
entries = ["CSS", "Django", "Git", "HTML", "Python"]


# Use django forms to generate fields for create page
class NewEntryForm(forms.Form):
    entry_title = forms.CharField(label="Title")
    entry_markdown = forms.CharField(widget=forms.Textarea)

# Create a separate Edit form to allow only edit of textarea 
class EditEntryForm(forms.Form):
    entry_markdown = forms.CharField(widget=forms.Textarea)

#Define home page view
def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

#Define entry page view
def entry(request, title):
    entry_string = util.get_entry(title)
    error_message = "Could not find your file. Please try again."
    if entry_string:
        converted_md = markdowner.convert(entry_string)
        return render(request, "encyclopedia/entry.html", {
            "title": title.capitalize(),
            "markdown": converted_md
        })
    else:
        return render(request, "encyclopedia/error.html", {
            "error_message": error_message
        }) 

#Define edit page view
def edit_page(request, title):
    content = util.get_entry(title)
    print(content)
    
    form = EditEntryForm(request.POST or None, initial={'entry_markdown': util.get_entry(title)})
    if form.is_valid():
        entry_markdown = form.cleaned_data["entry_markdown"]
        util.save_entry(title, entry_markdown)
        converted_md = markdowner.convert(entry_markdown)
        return render(request, "encyclopedia/entry.html", {
            "title": title.capitalize(),
            "markdown": converted_md
        })
    else:
        # form.fields['entry_markdown'].initial = util.get_entry(title)
        return render(request, "encyclopedia/edit.html", {
            "form": form,
            "title": title
        })

#Define create page view
def create(request):
    if request.method == "POST":
        form = NewEntryForm(request.POST)
        
        if form.is_valid():
            title = form.cleaned_data["entry_title"]
            entry_markdown = form.cleaned_data["entry_markdown"]
            print(title)
            if title == util.get_entry(title):
                raise ValidationError(f"This title already exists")
            util.save_entry(title, entry_markdown)
            # return HttpResponseRedirect(reverse(entry, args=(title,)))
            converted_md = markdowner.convert(entry_markdown)
            return render(request, "encyclopedia/entry.html", {
                "title": title.capitalize(),
                "markdown": converted_md
            })
        else:
            return render(request, "encyclopedia/create.html", {
                "form": form
            })


    return render(request, "encyclopedia/create.html", {
        "form": NewEntryForm()
    })

#Define error page view
def error(request):
    return render(request, "encyclopedia/error.html")


#Define random page view
def random_page(request):
    entries = util.list_entries()
    title = random.choice(entries)
    entry_string = util.get_entry(title)
    converted_md = markdowner.convert(entry_string)
    # return HttpResponseRedirect(reverse('random', args=(random_page,)))
    return render(request, "encyclopedia/random.html", {
                "title": title.capitalize(),
                "markdown": converted_md
            })

#Define search page view
def search(request):
    q = request.GET.get('q', '')
    entry_string = util.get_entry(q)
    if q is None:
        return render(request, 'encyclopedia/error.html')
    elif entry_string != None:
        converted_md = markdowner.convert(entry_string)
        return render(request, "encyclopedia/entry.html", {
            "title": q.capitalize(),
            "markdown": converted_md
        })
    else:
        sub_string = []
        for title in util.list_entries():
            if q in title:
                sub_string.append(title)

        return render(request, "encyclopedia/search.html", {
            "entries": sub_string
        })

Project-1/wiki/encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia Create Entry
{% endblock %}

{% block body %}
<h1>Create a New Page</h1>
<form class="create-entry" action="{% url 'encyclopedia:create' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
</form>

{% endblock %}

Project-1/wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia {{ title }}
{% endblock %}

{% block body %}
    <h1>Edit Entry - {{ title }}</h1>
    
    <div class="pseudo-label">
        <b>Title</b>
        <span>{{ title }}</span>
    </div>

    <!-- <div class="pseudo-label">
        <b>Markdown</b>
        <span>{{ markdown|safe }}</span>
    </div> -->

    <form action="{% url 'encyclopedia:edit' title %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
   

{% endblock %}

Project-1/wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia {{ title }}
{% endblock %}

{% block body %}
    <h1>Entry - {{ title }}</h1>
    
    <div class="pseudo-label">
        <b>Title</b>
        <span>{{ title }}</span>
    </div>

    <div class="pseudo-label">
        <b>Markdown</b>
        <span>{{ markdown }}</span>
        <a href="#" class="edit-markdown"><i class="fa-solid fa-pen"></i> Edit</a>
    </div>
   

{% endblock %}

Project-1/wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia Error
{% endblock %}

{% block body %}
<h1>Entry Not Found</h1>
<p>{{ error_message }}</p>
{% endblock %}

Project-1/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia Home
{% endblock %}

{% block body %}
    <h1>Home - All Pages</h1>

    <ul class="entries">
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

Project-1/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <script src="https://kit.fontawesome.com/ffa8d57923.js" crossorigin="anonymous"></script>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Zen+Kaku+Gothic+Antique:wght@300;400;500;700&display=swap" rel="stylesheet">
        <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> -->
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <header>
            <span>Project 1 - Wiki</span>
        </header>
        <div class="main-content-wrapper flex-wrapper">
            <aside>
                <strong>Wiki</strong>
                <form action="/wiki/" method="GET">
                    <input class="search" aria-label="search box" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <nav>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </nav>
                    
                {% block nav %}
                {% endblock %}
            </aside>
            <main class="">
                {% block body %}
                {% endblock %}
            </main>
        </div>
        <footer>
            <span>CSCI E-33a</span>
            <span>Project 1</span>
            <span>Reina McCuskey</span>
        </footer>
    </body>
</html>

Project-1/wiki/encyclopedia/templates/encyclopedia/random.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia {{ title }}
{% endblock %}

{% block body %}
    <h1>Random Entry - {{ title }}</h1>
    
    <div class="pseudo-label">
        <b>Title</b>
        <span>{{ title }}</span>
    </div>

    <div class="pseudo-label">
        <b>Markdown</b>
        <span>{{ markdown|safe }}</span>
    </div>
   

{% endblock %}

Project-1/wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia Search
{% endblock %}

{% block body %}
<h1>Search Results</h1>

<ul class="entries">
    {% for entry in entries %}
        <li><a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a></li>
    {% endfor %}
</ul>
    

{% endblock %}